### ISSUE TITLE
caminfo issue 

### ISSUE THREAD

**Issue by moshanATucsd** [Zihan-Wang/IMUsimulation#29]
in `/kitti/camera_color_left/camera_info`, the values are 
```
---
header: 
  seq: 0
  stamp: 
    secs: 18
    nsecs: 400629999
  frame_id: "camera_color_left"
height: 370
width: 1226
distortion_model: ''
D: []
K: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
R: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
P: [707.0912, 0.0, 601.8873, 46.88783, 0.0, 707.0912, 183.1104, 0.1178601, 0.0, 0.0, 1.0, 0.006203223]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
but normally it should be 
```
---
header: 
  seq: 496
  stamp: 
    secs: 130
    nsecs: 920000000
  frame_id: "falcon/cam_left"
height: 480
width: 640
distortion_model: "plumb_bob"
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [260.99805320956386, 0.0, 320.0, 0.0, 260.99805320956386, 240.0, 0.0, 0.0, 1.0]
R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
P: [260.99805320956386, 0.0, 320.0, 0.0, 0.0, 260.99805320956386, 240.0, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
```
K should be set, also note that D should not be empty!
